# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 382)
        MainWindow.setMinimumSize(QtCore.QSize(295, 382))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 382))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(35, 36))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.songsView = QtWidgets.QTableWidget(self.centralwidget)
        self.songsView.setMinimumSize(QtCore.QSize(251, 0))
        self.songsView.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.songsView.setObjectName("songsView")
        self.songsView.setColumnCount(0)
        self.songsView.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.songsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.currentTrack = QtWidgets.QLabel(self.centralwidget)
        self.currentTrack.setMinimumSize(QtCore.QSize(256, 21))
        self.currentTrack.setMaximumSize(QtCore.QSize(256, 21))
        self.currentTrack.setAutoFillBackground(True)
        self.currentTrack.setText("")
        self.currentTrack.setObjectName("currentTrack")
        self.verticalLayout.addWidget(self.currentTrack)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(35, 36))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setMaximumSize(QtCore.QSize(35, 35))
        self.Back.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon2)
        self.Back.setIconSize(QtCore.QSize(35, 35))
        self.Back.setObjectName("Back")
        self.horizontalLayout.addWidget(self.Back)
        self.Play = QtWidgets.QPushButton(self.centralwidget)
        self.Play.setMaximumSize(QtCore.QSize(50, 35))
        self.Play.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play.setIcon(icon3)
        self.Play.setIconSize(QtCore.QSize(50, 35))
        self.Play.setObjectName("Play")
        self.horizontalLayout.addWidget(self.Play)
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setEnabled(True)
        self.Next.setMaximumSize(QtCore.QSize(35, 35))
        self.Next.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Next.setIcon(icon4)
        self.Next.setIconSize(QtCore.QSize(35, 35))
        self.Next.setObjectName("Next")
        self.horizontalLayout.addWidget(self.Next)
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setMaximumSize(QtCore.QSize(20, 20))
        self.Stop.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop.setIcon(icon5)
        self.Stop.setIconSize(QtCore.QSize(20, 20))
        self.Stop.setObjectName("Stop")
        self.horizontalLayout.addWidget(self.Stop)
        self.Volume = QtWidgets.QSlider(self.centralwidget)
        self.Volume.setMaximum(100)
        self.Volume.setProperty("value", 100)
        self.Volume.setTracking(True)
        self.Volume.setOrientation(QtCore.Qt.Horizontal)
        self.Volume.setObjectName("Volume")
        self.horizontalLayout.addWidget(self.Volume)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.playlistView = QtWidgets.QTableWidget(self.centralwidget)
        self.playlistView.setMinimumSize(QtCore.QSize(256, 211))
        self.playlistView.setMaximumSize(QtCore.QSize(256, 211))
        self.playlistView.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.playlistView.setObjectName("playlistView")
        self.playlistView.setColumnCount(0)
        self.playlistView.setRowCount(0)
        self.verticalLayout.addWidget(self.playlistView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setMaximumSize(QtCore.QSize(75, 23))
        self.Add.setObjectName("Add")
        self.horizontalLayout_3.addWidget(self.Add)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.Clear = QtWidgets.QPushButton(self.centralwidget)
        self.Clear.setMaximumSize(QtCore.QSize(75, 23))
        self.Clear.setObjectName("Clear")
        self.horizontalLayout_3.addWidget(self.Clear)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProperties = QtWidgets.QMenu(self.menubar)
        self.menuProperties.setObjectName("menuProperties")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setObjectName("actionSelect")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionAdd_more = QtWidgets.QAction(MainWindow)
        self.actionAdd_more.setObjectName("actionAdd_more")
        self.actionClear_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_2.setObjectName("actionClear_2")
        self.menuFile.addAction(self.actionSelect)
        self.menuFile.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProperties.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.pushButton_2.setText(_translate("MainWindow", "Google"))
        self.Clear.setText(_translate("MainWindow", "Clear"))
        self.progressBar.setFormat(_translate("MainWindow", "00:00"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProperties.setTitle(_translate("MainWindow", "Properties"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSelect.setText(_translate("MainWindow", "Select"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionAdd_more.setText(_translate("MainWindow", "Add more"))
        self.actionClear_2.setText(_translate("MainWindow", "Clear"))

