# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 360)
        MainWindow.setMinimumSize(QtCore.QSize(504, 360))
        MainWindow.setMaximumSize(QtCore.QSize(504, 360))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(10, 270, 75, 23))
        self.Add.setObjectName("Add")
        self.Clear = QtWidgets.QPushButton(self.centralwidget)
        self.Clear.setGeometry(QtCore.QRect(420, 270, 75, 23))
        self.Clear.setObjectName("Clear")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 310, 441, 20))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(330, 25, 20, 20))
        self.Stop.setMaximumSize(QtCore.QSize(20, 20))
        self.Stop.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop.setIcon(icon)
        self.Stop.setIconSize(QtCore.QSize(20, 20))
        self.Stop.setObjectName("Stop")
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setEnabled(True)
        self.Next.setGeometry(QtCore.QRect(285, 10, 35, 35))
        self.Next.setMaximumSize(QtCore.QSize(35, 35))
        self.Next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Next.setIcon(icon1)
        self.Next.setIconSize(QtCore.QSize(35, 35))
        self.Next.setObjectName("Next")
        self.Play = QtWidgets.QPushButton(self.centralwidget)
        self.Play.setGeometry(QtCore.QRect(227, 10, 50, 35))
        self.Play.setMaximumSize(QtCore.QSize(50, 35))
        self.Play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play.setIcon(icon2)
        self.Play.setIconSize(QtCore.QSize(50, 35))
        self.Play.setObjectName("Play")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(185, 10, 35, 35))
        self.Back.setMaximumSize(QtCore.QSize(35, 35))
        self.Back.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon3)
        self.Back.setIconSize(QtCore.QSize(35, 35))
        self.Back.setObjectName("Back")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 35, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("google.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(35, 36))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 300, 35, 35))
        self.pushButton_2.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 36))
        self.pushButton_2.setObjectName("pushButton_2")
        self.currentTrack = QtWidgets.QLabel(self.centralwidget)
        self.currentTrack.setGeometry(QtCore.QRect(90, 270, 321, 21))
        self.currentTrack.setAutoFillBackground(True)
        self.currentTrack.setText("")
        self.currentTrack.setObjectName("currentTrack")
        self.Volume = QtWidgets.QSlider(self.centralwidget)
        self.Volume.setGeometry(QtCore.QRect(370, 20, 121, 22))
        self.Volume.setMaximum(100)
        self.Volume.setProperty("value", 100)
        self.Volume.setTracking(True)
        self.Volume.setOrientation(QtCore.Qt.Horizontal)
        self.Volume.setObjectName("Volume")
        self.playlistView = QtWidgets.QTableWidget(self.centralwidget)
        self.playlistView.setGeometry(QtCore.QRect(250, 50, 256, 211))
        self.playlistView.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.playlistView.setObjectName("playlistView")
        self.playlistView.setColumnCount(0)
        self.playlistView.setRowCount(0)
        self.songsView = QtWidgets.QTableWidget(self.centralwidget)
        self.songsView.setGeometry(QtCore.QRect(0, 50, 251, 211))
        self.songsView.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.songsView.setObjectName("songsView")
        self.songsView.setColumnCount(0)
        self.songsView.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuProperties = QtWidgets.QMenu(self.menubar)
        self.menuProperties.setObjectName("menuProperties")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setObjectName("actionSelect")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionAdd_more = QtWidgets.QAction(MainWindow)
        self.actionAdd_more.setObjectName("actionAdd_more")
        self.actionClear_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_2.setObjectName("actionClear_2")
        self.menuFile.addAction(self.actionSelect)
        self.menuFile.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProperties.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Clear.setText(_translate("MainWindow", "Clear"))
        self.progressBar.setFormat(_translate("MainWindow", "00:00"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuProperties.setTitle(_translate("MainWindow", "Properties"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSelect.setText(_translate("MainWindow", "Select"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionAdd_more.setText(_translate("MainWindow", "Add more"))
        self.actionClear_2.setText(_translate("MainWindow", "Clear"))

